name: Deploy Lambda functions and Layer

on:
  push:
    branches:
      - main
      - pipeline_test
    # pull_request:
    #   types:
    #     - opened
    #     - synchronize
    paths:
      - "python/user_settings_lambda/**"

env:
  AWS_DEFAULT_REGION: "ap-northeast-1"
  FUNCTION_DIR: "user_settings_lambda"
  FUNCTION_NAME: "train-prd-lambda-user-settings"

jobs:
  deploy_template:
    environment: AWS_PRD
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Build
        run: |
          echo "Building from directory: python/${{ env.FUNCTION_DIR }}"
          mkdir ./tmp
          cd python/${{ env.FUNCTION_DIR }}
          zip -r ../../tmp/${{ env.FUNCTION_DIR }}.zip *
        working-directory: ${{ github.workspace }}

      - name: Deploy
        run: |
          echo "Deploying from directory: python/${{ env.FUNCTION_DIR }}"
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --zip-file fileb://./tmp/${{ env.FUNCTION_DIR }}.zip
        working-directory: ${{ github.workspace }}
