name: Deploy Lambda functions and Layer

on:
  push:
    branches:
      - main
      - pipeline_test
    # pull_request:
    #   types:
    #     - opened
    #     - synchronize
    paths:
      - "python/user_settings_lambda/**"

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Build
        run: |
          echo "Building from directory: python/${{ inputs.FUNCTION_DIR }}"
          mkdir ./tmp
          cd python/${{ inputs.FUNCTION_DIR }}
          zip -r ./tmp/${{ inputs.FUNCTION_DIR }}.zip *
        working-directory: ${{ github.workspace }}

      - name: Deploy
        run: |
          echo "Deploying from directory: python/${{ inputs.FUNCTION_DIR }}"
          cd ./tmp
          aws lambda update-function-code --function-name ${{ inputs.FUNCTION_NAME }} --zip-file fileb:./${{ inputs.FUNCTION_DIR }}.zip
        working-directory: ${{ github.workspace }}
